name: flutter_bridge
description: A Flutter bridge SDK for communication between Flutter and WebView
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  shared_preferences: ^2.2.0
  i18n:
    path: ../i18n
  http: ^1.2.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.0
  flutter_local_notifications: ^17.2.0
  archive: ^3.6.0
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  nyanya_webview:
    path: ../../../../../lib/nyanya-webview
  tencent_kit: ^6.2.0
  app_update:
    path: ../app_update
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
