name: flutter_app
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.13+466

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^6.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.0
  package_info_plus: ^8.0.0
  flutter_local_notifications: ^17.2.0
  wakelock_plus: ^1.2.1
  url_launcher: ^6.3.1
  http: ^1.2.0
  path_provider: ^2.1.0

  cupertino_icons: ^1.0.8

  shelf: ^1.4.1
  shelf_static: ^1.1.2

  flutter_bridge:
    path: modules/flutter_bridge
  i18n:
    path: modules/i18n
  nyanya_webview:
    git:
      url: https://github.com/ShiinaAiiko/nyanya-webview.git
      branch: v1.0.0
  shadcn_ui: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

dependency_overrides:
  nyanya_webview:
    path: ../../../lib/nyanya-webview

flutter:
  uses-material-design: true

  assets:
    - assets/out/
    - assets/out/_next/
    - assets/out/_next/F6l6EsAL3FomdK5Y6p2M5/
    - assets/out/_next/data/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/en-US/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/en-US/journeyMemories/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/en-US/trip/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-CN/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-CN/journeyMemories/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-CN/trip/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-TW/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-TW/journeyMemories/
    - assets/out/_next/data/F6l6EsAL3FomdK5Y6p2M5/zh-TW/trip/
    - assets/out/_next/static/
    - assets/out/_next/static/F6l6EsAL3FomdK5Y6p2M5/
    - assets/out/_next/static/chunks/
    - assets/out/_next/static/chunks/pages/
    - assets/out/_next/static/chunks/pages/[lang]/
    - assets/out/_next/static/chunks/pages/[lang]/journeyMemories/
    - assets/out/_next/static/chunks/pages/[lang]/trip/
    - assets/out/_next/static/chunks/pages/journeyMemories/
    - assets/out/_next/static/chunks/pages/trip/
    - assets/out/_next/static/css/
    - assets/out/css/
    - assets/out/en-US/
    - assets/out/en-US/journeyMemories/
    - assets/out/en-US/trip/
    - assets/out/fonts/
    - assets/out/icons/
    - assets/out/images/
    - assets/out/images/mapThumbnail/
    - assets/out/images/mapThumbnail/small/
    - assets/out/journeyMemories/
    - assets/out/js/
    - assets/out/saki-ui/
    - assets/out/saki-ui/assets/
    - assets/out/saki-ui/css/
    - assets/out/trip/
    - assets/out/zh-CN/
    - assets/out/zh-CN/journeyMemories/
    - assets/out/zh-CN/trip/
    - assets/out/zh-TW/
    - assets/out/zh-TW/journeyMemories/
    - assets/out/zh-TW/trip/
