name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+4113

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sensors_plus: ^6.1.2
  permission_handler: ^11.3.1
  geolocator: ^12.0.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

  shelf: ^1.4.1
  shelf_static: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/out/
    - assets/out/_next/
    - assets/out/_next/TUIRJ2lwk8eH6cTtxy5KQ/
    - assets/out/_next/data/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/en-US/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/en-US/journeyMemories/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/en-US/trip/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-CN/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-CN/journeyMemories/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-CN/trip/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-TW/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-TW/journeyMemories/
    - assets/out/_next/data/TUIRJ2lwk8eH6cTtxy5KQ/zh-TW/trip/
    - assets/out/_next/static/
    - assets/out/_next/static/TUIRJ2lwk8eH6cTtxy5KQ/
    - assets/out/_next/static/chunks/
    - assets/out/_next/static/chunks/pages/
    - assets/out/_next/static/chunks/pages/[lang]/
    - assets/out/_next/static/chunks/pages/[lang]/journeyMemories/
    - assets/out/_next/static/chunks/pages/[lang]/trip/
    - assets/out/_next/static/chunks/pages/journeyMemories/
    - assets/out/_next/static/chunks/pages/trip/
    - assets/out/_next/static/css/
    - assets/out/css/
    - assets/out/en-US/
    - assets/out/en-US/journeyMemories/
    - assets/out/en-US/trip/
    - assets/out/fonts/
    - assets/out/icons/
    - assets/out/images/
    - assets/out/images/mapThumbnail/
    - assets/out/images/mapThumbnail/small/
    - assets/out/journeyMemories/
    - assets/out/js/
    - assets/out/saki-ui/
    - assets/out/saki-ui/assets/
    - assets/out/saki-ui/css/
    - assets/out/trip/
    - assets/out/zh-CN/
    - assets/out/zh-CN/journeyMemories/
    - assets/out/zh-CN/trip/
    - assets/out/zh-TW/
    - assets/out/zh-TW/journeyMemories/
    - assets/out/zh-TW/trip/
